### ISSUE TITLE
DETS keeps getting corrupted

### ISSUE THREAD

**Issue by houshuang** [ferd/erlang-history#17]
I think this is an absolutely crucial feature, and I appreciate your development. I'm using it through Elixir/IEx, and unfortunately I get a message that my DETS file is corrupted every time I start IEx, and when I type up in a new session, I get the same suggestions from a very old session every time - until I delete the DETS file.

I wonder if it is because I we usually close IEx with Ctrl+C Ctrl+C? I tried closing with System.halt, and that seemed (only tried a few times) to properly flush the DETS file, however if I were in a remote REPL, System.halt would, I believe, also end that process. Also it's annoying to type :) 

Not sure how to fix - perhaps flushing to disk more often?

**Comment by ferd** [comment]
No idea. The problem is in DETS and it's why I never pushed to have this anywhere. Can't ever fix.

**Comment by henrik** [comment]
In case anyone else wants to uninstall due to this issue, this is how I did it: https://gist.github.com/henrik/9e5250a83ccec6891f29e17f3f37277f

(I'm sure there are better ways. Do let me know.)

**Comment by utkarshkukreti** [comment]
@henrik I just did `brew reinstall erlang` IIRC and that worked fine.

**Comment by henrik** [comment]
@utkarshkukreti 👍 I considered reinstalling but didn't realise it was quite that simple :)

**Comment by h4cc** [comment]
Is there a command to fix this issue? Maybe a simple one provided by this module.

**Comment by ferd** [comment]
There is no command. DETS tries to repair files on its own but I have never seen it succeed.

**Comment by ferd** [comment]
See https://github.com/ferd/erlang-history/pull/29 for a possible fix
