### ISSUE TITLE
Erro on make install - Ubuntu

### ISSUE THREAD

**Issue by victorlcampos** [ferd/erlang-history#19]
Hi guys,
I'm trying to install this and I'm getting this error:

root@visagio:/usr/local/src/erlang-history# make install
erl -make
{"init terminating in do_boot",{undef,[{make,all,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
make: *** [compile] User defined signal 2
root@visagio:/usr/local/src/erlang-history#

Could you help me?
I'm using ubuntu 14.2

**Comment by ferd** [comment]
You are probably missing development packages and only using runtime ones. Try looking for source/dev packages.

**Comment by victorlcampos** [comment]
But, do you know what is the dependencies?

**Comment by ferd** [comment]
No, I do not run Ubuntu. I do know however that the canonical packages for Erlang are always the smallest thing that can run pre-compiled packages and software. As such, they tend to avoid putting in stuff like `eunit` or other development-related libraries in Erlang. It's my guess that the [make](http://www.erlang.org/doc/man/make.html) module, part of the `tool` library, isn't included in the default packages.

Look for 'erlang-dev' or something like that.

**Comment by victorlcampos** [comment]
victorlcampos@visagio:~/Workspaces/Vale/ajustedataves$ sudo apt-get install erlang-dev
[sudo] password for victorlcampos: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
erlang-dev is already the newest version.

**Comment by ferd** [comment]
Then I don't know, but your install is to blame. The make module: http://www.erlang.org/doc/man/make.html is part of the standard distribution. The error you showed, `{undef,[{make,all,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}` is telling you that it cannot be found. This problem isn't with this library, but I can't help further as I do not know what your setup is.

**Comment by lasseebert** [comment]
I had the same problem on Ubuntu. It seems that I never installed erlang directly, only elixir via a ppa, which has some dependencies to some but not all erlang packages.

Just installing `erlang` helped.

```
sudo apt-get install erlang
```
