### ISSUE TITLE
Installation issue on Linux

### ISSUE THREAD

**Issue by Qqwy** [ferd/erlang-history#21]
I have installed `erlang` and `erlang-dev` (as outlined in #19 ), but when running `make install` I get the following stack trace:

~~~
make install
erl -make
./install.escript
Path = /usr/lib/erlang/lib/kernel-4.2/ebin
Version = 4.2
group_history already in modules list of kernel.app
Backup of group.beam exists
Installing...
cp: cannot stat \x{2018}ebin/4.2/*.beam\x{2019}: No such file or directory
~~~

It seems to me that the character substitution goes wrong for some reason.

I am using Linux Mint 17.2

**Comment by ferd** [comment]
`ebin/4.2/*.beam` makes it sound like the original compilation failed. Is there anything in `ebin/4.2/` of this repository?

**Comment by ferd** [comment]
Closing this for being inactive.
