### ISSUE TITLE
README underpromises on history search

### ISSUE THREAD

**Issue by ivan** [ferd/erlang-history#24]
[The README](https://github.com/ferd/erlang-history#does-this-handle-more-advanced-history-functionality-than-just-updown-arrows) claims ^R / history search doesn't work, but it seems to be implemented in `group.erl` and it works fine here.  Thank you for making all of this work!

**Comment by ferd** [comment]
The ^R search is a thing I've added into OTP itself. It doesn't work in older versions of Erlang-history since there is no built in support.
