### ISSUE TITLE
Missing ebin for kernel "5.0.2"

### ISSUE THREAD

**Issue by h4cc** [ferd/erlang-history#27]
This wonderful tool (thanks!) does not work for my system :(

```
1> application:which_applications().
[{stdlib,"ERTS  CXC 138 10","3.0.1"},
 {kernel,"ERTS  CXC 138 10","5.0.2"}]
```

**Comment by ferd** [comment]
Is this a patch release? I only tend to cover major ones. If you've got a patch release, that would explain it. See in [the README](https://github.com/ferd/erlang-history#what-versions-of-erlangotp-does-this-work-with):

> I've tested it with all quarterly versions from R13B04 up to 19.2. It worked fine for them. I plan on supporting all newer quarterly versions. ALL OF THEM.
>
> To be noted is that since release 17.0, the OTP team may silently release intermediary versions of Erlang/OTP on github as patches. An example of this is Erlang 17.2, which was never announced, but is installable for people who need it. Those are not supported explicitly, but pull requests are welcome.

I don't necessarily have the time to go fetch every patch release (there's sometimes 4 or more for any one of them) so I tend to only care about the non-patch quarterly ones as a thing provided by default.

**Comment by h4cc** [comment]
Thank your very much for that information!

I tried to find out my currently installed erlang on my Xubuntu 16.04 notebook:

```
dpkg -l | grep erlang
ii esl-erlang 1:19.0.7 ...
```

Erlang shell:
```
$ erl
Erlang/OTP 19 [erts-8.0.5] [source-99c6fd1] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.0.5  (abort with ^G)
1>
```

It seems to be the 19.0.7 from erlang solutions: https://www.erlang-solutions.com/resources/download.html

Either i simply upgrade my erlang version or try to fix it myself, dont bother too much about this :D
