### ISSUE TITLE
Add support for Erlang/OTP 20

### ISSUE THREAD

**Issue by shymega** [ferd/erlang-history#34]

**Comment by ferd** [comment]
The support for shell history has been added directly to OTP-20rc2 -- although disabled by default. 

Since I've ported it here, OTP 19 is the last major release supported here

**Comment by shymega** [comment]
Hi,

Fred Hebert <notifications@github.com> writes:

> The support for shell history has been added directly to OTP-20rc2
> -- although disabled by default.
>
> Since I've ported it here, OTP 19 is the last major release
> supported here

Oops, my bad. Might I suggest that you put an entry in the FAQ for
this repository to let people know that OTP 20 has it built-in --- for
those, like myself, who might have overlooked that?

Thanks :smile:

-- 
Kind regards,
Dom Rodriguez (shymega/dzr{_,})

"Freedom is the freedom to say two plus two make four.
 If that is granted, all else follows."
	-- George Orwell, Nineteen Eighty-Four.

**Comment by ferd** [comment]
Yeah I will in the upcoming days
