### ISSUE TITLE
Hallelujah!!

### ISSUE THREAD

**Issue by 7stud** [ferd/erlang-history#36]
After typing the same shell commands over an over again for the past 24 hours, I was searching around trying to solve an erlang error, and I happened upon [10 Essential Erlang Tools for Erlang Developers](https://www.pluralsight.com/guides/erlang/10-essential-erlang-tools-for-erlang-developers), which piqued my interest, so I decided to stop in for a look.  Salvation! 

Thank you.

**Comment by fenollp** [comment]
@7stud https://twitter.com/mononcqc/status/877544929496629248

**Comment by ferd** [comment]
Thanks for the comments!
