### ISSUE TITLE
Way to Clean up saved history

### ISSUE THREAD

**Issue by mangalakader** [ferd/erlang-history#38]
Hi @ferd ,

Currently, the group history doesn't export a clean up function for cleaning the saved history. But since you are using disk_log for later versions of erlang, you can indirectly export the truncate function in the disk_log module for cleaning up the saved history. I could do a PR if that would help speed up the process...

Thank you,

**Comment by ferd** [comment]
This code is no longer maintained, the official versions lives in the OTP repository. I just forgot to archive the repository.
