### ISSUE TITLE
erlang-history should include patches, not actual files

### ISSUE THREAD

**Issue by baryluk** [ferd/erlang-history#4]
I think it is better, or additionally to have synchronized patch files, so it is easier to apply them to newer kernel app versions. 

Another issue, is to allow different code search path, so old files doesn't need to be overwritten.

The best way would be to allow dynamic patching of modules, but this would probably be hard to achive (especially considering performance and code-reloading). I guess, other possibility is to tell OTP team, to provide required hooks, so we can plug in (with elegant behaviour/callbacks description).

**Comment by ferd** [comment]
Inactive for years. Probably not gonna happen since the current scheme works pretty well for me, even though patches would objectively be lighter of a process.
